version: '2'
volumes:
  data-pgadmin:
services:
  db:
    container_name: db-odoo
    image: postgres:11.6
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
        - odoo-db:/var/lib/postgresql/data
    restart: always
  odoo13-webserver:
    container_name: server-odoo
    image: w2s2k/odoo13-multiarch:1.0
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
    tty: true
    command: -- --dev=reload
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - odoo-data:/var/lib/odoo
    restart: always
networks:
    default:
        name: frontend