version: '2'
volumes:
  data-pgadmin:
services:
  db:
    container_name: odoo13-postgres
    image: postgres:11.6
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
        - ./postgresql:/var/lib/postgresql/data
    restart: always
  odoo13-webserver:
    container_name: odoo13-webserver
    image: w2s2k/odoo13-multiarch:1.0
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
    tty: true
    command: -- --dev=reload
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - ./filestore:/var/lib/odoo/filestore
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
        - ./postgresql:/var/lib/postgresql/data
        - ./pgadmin:/var/lib/pgadmin/storage
    depends_on:
      - db
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped

networks:
    default:
        name: frontend